### ISSUE TITLE
Where are you in this project?

### ISSUE THREAD

**Issue by greenpdx** [robbym/json-wsp-rs#1]
I am looking to find out more information on  json-wsp.  Right now I am using https://github.com/paritytech/jsonrpc for my server, there are some issues. I would like to switch to https://github.com/actix/actix-web  for json commands. do you have a the docs? or a JS library?

**Comment by robbym** [comment]
Sorry, no I do not. I haven't touched this in quite some time. I do remember that I used Ladon (python library).

**Comment by greenpdx** [comment]
thanks
